 export const DataGarage = [
    {
      id: '1',
      name: 'Nhà xe Hữu Trưởng',
      status: 'available',
      capacity: 60,
      address: '280 Lê Hồng Phong, phường 7, quận 5',
      phone: '0274114118',
      timeWorking: '4:00 - 23:30',
      discription: '',
    },
    {
      id: '2',
      name: 'Nhà xe Tiến Thành',
      status: 'not available',
      capacity: 60,
      address: '30 Lý Chính Thắng, phường 2, quận 3',
      phone: '0274114118',
      timeWorking: '8:00 - 22:00',
      discription: '',
    },
    {
      id: '3',
      name: 'Nhà xe Huế Như',
      status: 'available',
      capacity: 60,
      address: '11 Nguyễn Văn Linh, phường Bình Phương, quận 7',
      phone: '0274114118',
      timeWorking: '7:00 - 17:00',
      discription: '',
    },
    {
      id: '4',
      name: 'Nhà xe Thiện Toàn',
      status: 'not available',
      capacity: 60,
      address: '69 Phạm Văn Đồng, phường Linh Trung, quận Thủ Đức',
      phone: '0274114118',
      timeWorking: '6:00 - 22:00',
      discription: '',
    },
    {
      id: '5',
      name: 'Nhà xe Trung Trực sieeu cap provjp',
      status: 'available',
      capacity: 60,
      address: '33 Nguyễn Văn Cừ, phường 1, quận 5',
      phone: '0274114118',
      timeWorking: '9:00 - 22:00',
      discription: '',
    },
    {
      id: '6',
      name: 'Nhà xe Xuân Vũ',
      status: 'not available',
      capacity: 60,
      address: '82 Nguyễn Thị Minh Khai, phường 2, quận 1',
      phone: '0274114118',
      timeWorking: '9:00 - 22:00',
      discription: '',
    },
    {
      id: '7',
      name: 'Nhà xe Hữu Trưởng',
      status: 'available',
      capacity: 60,
      address: '280 Lê Hồng Phong, phường 7, quận 5',
      phone: '0274114118',
      timeWorking: '9:00 - 22:00',
      discription: '',
    },
    {
      id: '8',
      name: 'Nhà xe Tiến Thành',
      status: 'available',
      capacity: 60,
      address: '30 Lý Chính Thắng, phường 2, quận 3',
      phone: '0274114118',
      timeWorking: '9:00 - 22:00',
      discription: '',
    },
    {
      id: '9',
      name: 'Nhà xe Huế Như',
      status: 'available',
      capacity: 60,
      address: '11 Nguyễn Văn Linh, phường Bình Phương, quận 7',
      phone: '0274114118',
      timeWorking: '9:00 - 22:00',
      discription: '',
    },
    {
      id: '10',
      name: 'Nhà xe Thiện Toàn',
      status: 'available',
      capacity: 60,
      address: '69 Phạm Văn Đồng, phường Linh Trung, quận Thủ Đức',
      phone: '0274114118',
      timeWorking: '9:00 - 22:00',
      discription: '',
    },
    {
      id: '11',
      name: 'Nhà xe Xuân Vũ Nguyễn Tiến Thành Siêu cấp provjp đệ nhất thiên hạ',
      status: 'available',
      capacity: 60,
      address: '33 Nguyễn Văn Cừ, phường 1, quận 5',
      phone: '0274114118',
      timeWorking: '9:00 - 22:00',
      discription: '',
    },
    {
      id: '12',
      name: 'Nhà xe Xuân Vũ Nguyễn Tiến Thành Siêu cấp provjp đệ nhất thiên hạ',
      status: 'available',
      capacity: 60,
      address: '82 Nguyễn Thị Minh Khai, phường 2, quận 1',
      phone: '0274114118',
      timeWorking: '9:00 - 22:00',
      discription: '',
    },
];